import { hashToken } from "@/lib/utils";
import type { AcceptanceItem, Requirement, RoleTask } from "@/lib/types";
import type { DatabaseSnapshot } from "@/lib/db/local-store";

/** 固定 ID，保证 Vercel 多实例与刷新后链接仍有效 */
export const SEED_IDS = {
  petProject: "proj-ai-pet",
  controllerProject: "proj-ai-controller",
  petIter: "iter-ai-pet-202606",
  controllerIter: "iter-ai-controller-202604",
  petReqHome: "req-pet-home",
  petReqBanner: "req-pet-banner",
  petReqPush: "req-pet-push",
  ctrlReqMask: "req-ctrl-mask",
  ctrlReqMigrate: "req-ctrl-migrate",
} as const;

const SEED_TIME = "2026-06-22T00:00:00.000Z";

export function createSeedData(): DatabaseSnapshot {
  const petProjectId = SEED_IDS.petProject;
  const controllerProjectId = SEED_IDS.controllerProject;
  const petIterationId = SEED_IDS.petIter;
  const controllerIterationId = SEED_IDS.controllerIter;

  const petReqs: Requirement[] = [
    {
      id: SEED_IDS.petReqHome,
      project_id: petProjectId,
      iteration_id: petIterationId,
      module_l1_id: null,
      module_l2_id: null,
      title: "主页页面整体结构优化",
      sub_function: null,
      detail_work: null,
      acceptance_criteria: "主页结构符合设计稿，导航与模块分区清晰",
      priority: null,
      status: "in_progress",
      blocker_reason: null,
      sort_order: 1,
      created_at: SEED_TIME,
      updated_at: SEED_TIME,
    },
    {
      id: SEED_IDS.petReqBanner,
      project_id: petProjectId,
      iteration_id: petIterationId,
      module_l1_id: null,
      module_l2_id: null,
      title: "安静状态下的陪伴专注横幅",
      sub_function: "安静状态下的陪伴专注横幅",
      detail_work: null,
      acceptance_criteria: "安静模式下正确展示专注横幅，交互符合 PRD",
      priority: null,
      status: "testing",
      blocker_reason: null,
      sort_order: 2,
      created_at: SEED_TIME,
      updated_at: SEED_TIME,
    },
    {
      id: SEED_IDS.petReqPush,
      project_id: petProjectId,
      iteration_id: petIterationId,
      module_l1_id: null,
      module_l2_id: null,
      title: "推送模块（推送/勿扰/喝水）",
      sub_function: null,
      detail_work: "后端整体评估 40 小时，覆盖三个子模块",
      acceptance_criteria: "推送、勿扰、喝水三条链路均可独立验收",
      priority: "P0",
      status: "in_progress",
      blocker_reason: null,
      sort_order: 3,
      created_at: SEED_TIME,
      updated_at: SEED_TIME,
    },
  ];

  const controllerReqs: Requirement[] = [
    {
      id: SEED_IDS.ctrlReqMask,
      project_id: controllerProjectId,
      iteration_id: controllerIterationId,
      module_l1_id: null,
      module_l2_id: null,
      title: "下控遮罩等待界面",
      sub_function: "下控遮罩等待界面",
      detail_work: null,
      acceptance_criteria: "下控流程中遮罩等待界面展示正确，超时处理符合规范",
      priority: "P0",
      status: "acceptance",
      blocker_reason: null,
      sort_order: 1,
      created_at: SEED_TIME,
      updated_at: SEED_TIME,
    },
    {
      id: SEED_IDS.ctrlReqMigrate,
      project_id: controllerProjectId,
      iteration_id: controllerIterationId,
      module_l1_id: null,
      module_l2_id: null,
      title: "设备归属和批量迁移",
      sub_function: "设备归属和批量迁移",
      detail_work: null,
      acceptance_criteria: "批量迁移后设备归属关系正确，日志可追溯",
      priority: "P0",
      status: "testing",
      blocker_reason: null,
      sort_order: 2,
      created_at: SEED_TIME,
      updated_at: SEED_TIME,
    },
  ];

  const petTasks: RoleTask[] = [
    {
      id: "task-pet-ui-home",
      requirement_id: petReqs[0].id,
      role: "ui",
      assignee: "游春梅",
      estimate_hours: null,
      actual_hours: null,
      start_date: null,
      end_date: null,
      status: "in_progress",
      notes: null,
      blocker_reason: null,
      progress_percent: 30,
      updated_at: SEED_TIME,
    },
    {
      id: "task-pet-fe-home",
      requirement_id: petReqs[0].id,
      role: "frontend",
      assignee: "陈伟平",
      estimate_hours: null,
      actual_hours: null,
      start_date: null,
      end_date: null,
      status: "pending",
      notes: null,
      blocker_reason: null,
      progress_percent: 0,
      updated_at: SEED_TIME,
    },
    {
      id: "task-pet-be-banner",
      requirement_id: petReqs[1].id,
      role: "backend",
      assignee: "李德堂",
      estimate_hours: 16,
      actual_hours: null,
      start_date: "2026-06-01",
      end_date: "2026-06-05",
      status: "testing",
      notes: "已提测",
      blocker_reason: null,
      progress_percent: 100,
      updated_at: SEED_TIME,
    },
    {
      id: "task-pet-fe-banner",
      requirement_id: petReqs[1].id,
      role: "frontend",
      assignee: "陈伟平",
      estimate_hours: 24,
      actual_hours: null,
      start_date: "2026-06-03",
      end_date: "2026-06-08",
      status: "testing",
      notes: null,
      blocker_reason: null,
      progress_percent: 100,
      updated_at: SEED_TIME,
    },
    {
      id: "task-pet-be-push",
      requirement_id: petReqs[2].id,
      role: "backend",
      assignee: "李德堂",
      estimate_hours: 40,
      actual_hours: null,
      start_date: "2026-06-01",
      end_date: "2026-06-15",
      status: "in_progress",
      notes: "模块级工时，覆盖推送/勿扰/喝水",
      blocker_reason: null,
      progress_percent: 21.32,
      updated_at: SEED_TIME,
    },
  ];

  const controllerTasks: RoleTask[] = [
    {
      id: "task-ctrl-be-mask",
      requirement_id: controllerReqs[0].id,
      role: "backend",
      assignee: "谢鑫",
      estimate_hours: 12,
      actual_hours: null,
      start_date: "2026-04-24",
      end_date: "2026-05-06",
      status: "acceptance",
      notes: null,
      blocker_reason: null,
      progress_percent: 100,
      updated_at: SEED_TIME,
    },
    {
      id: "task-ctrl-fe-mask",
      requirement_id: controllerReqs[0].id,
      role: "frontend",
      assignee: "陈伟平",
      estimate_hours: 4,
      actual_hours: null,
      start_date: "2026-04-27",
      end_date: "2026-05-15",
      status: "acceptance",
      notes: null,
      blocker_reason: null,
      progress_percent: 100,
      updated_at: SEED_TIME,
    },
    {
      id: "task-ctrl-be-migrate",
      requirement_id: controllerReqs[1].id,
      role: "backend",
      assignee: "谢鑫",
      estimate_hours: 8,
      actual_hours: null,
      start_date: null,
      end_date: null,
      status: "testing",
      notes: null,
      blocker_reason: null,
      progress_percent: 100,
      updated_at: SEED_TIME,
    },
  ];

  const acceptanceItems: AcceptanceItem[] = [
    {
      id: "acc-pet-home",
      requirement_id: petReqs[0].id,
      description: `${petReqs[0].title} - 功能符合 PRD`,
      passed: null,
      note: null,
      sort_order: 1,
    },
    {
      id: "acc-pet-banner",
      requirement_id: petReqs[1].id,
      description: `${petReqs[1].title} - 功能符合 PRD`,
      passed: false,
      note: "横幅在横屏下位置偏移",
      sort_order: 1,
    },
    {
      id: "acc-pet-push",
      requirement_id: petReqs[2].id,
      description: `${petReqs[2].title} - 功能符合 PRD`,
      passed: null,
      note: null,
      sort_order: 1,
    },
    {
      id: "acc-ctrl-mask",
      requirement_id: controllerReqs[0].id,
      description: `${controllerReqs[0].title} - 验收标准达成`,
      passed: null,
      note: null,
      sort_order: 1,
    },
    {
      id: "acc-ctrl-migrate",
      requirement_id: controllerReqs[1].id,
      description: `${controllerReqs[1].title} - 验收标准达成`,
      passed: null,
      note: null,
      sort_order: 1,
    },
  ];

  const frontendToken = "star-share-frontend-dev";
  const backendToken = "star-share-backend-dev";
  const testToken = "star-share-test-dev";

  return {
    projects: [
      {
        id: petProjectId,
        name: "AI 宠物",
        slug: "ai-pet",
        description: "宠物 App 优化需求管理",
        created_at: SEED_TIME,
      },
      {
        id: controllerProjectId,
        name: "AI 控制器",
        slug: "ai-controller",
        description: "元井 AI 控制器优化需求管理",
        created_at: SEED_TIME,
      },
    ],
    iterations: [
      {
        id: petIterationId,
        project_id: petProjectId,
        name: "20260610 优化版本",
        sort_order: 1,
        created_at: SEED_TIME,
      },
      {
        id: controllerIterationId,
        project_id: controllerProjectId,
        name: "20260417 元井AI控制器",
        sort_order: 1,
        created_at: SEED_TIME,
      },
    ],
    modules: [],
    requirements: [...petReqs, ...controllerReqs],
    acceptance_items: acceptanceItems,
    role_tasks: [...petTasks, ...controllerTasks],
    test_records: [],
    acceptance_records: [],
    share_links: [
      {
        id: "link-pet-frontend",
        project_id: petProjectId,
        role: "frontend",
        label: "前端协作链接",
        token_hash: hashToken(frontendToken),
        is_active: true,
        created_at: SEED_TIME,
        plain_token: frontendToken,
      },
      {
        id: "link-pet-backend",
        project_id: petProjectId,
        role: "backend",
        label: "后端协作链接",
        token_hash: hashToken(backendToken),
        is_active: true,
        created_at: SEED_TIME,
        plain_token: backendToken,
      },
      {
        id: "link-pet-test",
        project_id: petProjectId,
        role: "test",
        label: "测试协作链接",
        token_hash: hashToken(testToken),
        is_active: true,
        created_at: SEED_TIME,
        plain_token: testToken,
      },
    ],
    prototypes: [],
    prototype_annotations: [],
    bugs: [],
    notifications: [
      {
        id: "notif-pet-acceptance",
        project_id: petProjectId,
        recipient_name: "产品",
        type: "acceptance_pending",
        title: "2 条需求待产品验收",
        body: "安静状态下的陪伴专注横幅 等需求已进入待验收",
        link: "/projects/ai-pet/board",
        is_read: false,
        created_at: SEED_TIME,
      },
    ],
    activity_logs: [],
  };
}
