// @ts-nocheck — Wrangler entry; types checked via `npm run cf-typecheck` after `npm run cf-typegen`.
/**
 * Custom Cloudflare Worker entry: re-uses OpenNext fetch handler and adds Cron Triggers.
 * @see https://opennext.js.org/cloudflare/howtos/custom-worker
 */
// @ts-expect-error `.open-next/worker.js` is generated by `opennextjs-cloudflare build`
import { default as handler } from "./.open-next/worker.js";

/** Cron expression → existing Next.js cron route (Bearer CRON_SECRET). */
const CRON_ROUTES: Record<string, string> = {
  "0 9 * * *": "/api/cron/reminders",
  "0 10 * * *": "/api/cron/sync-ideas",
  "0 11 * * *": "/api/cron/sync-git",
};

export default {
  fetch: handler.fetch,

  async scheduled(controller, env) {
    const path = CRON_ROUTES[controller.cron];
    if (!path) {
      const msg = `[cron] unknown schedule: ${controller.cron}`;
      console.error(msg);
      throw new Error(msg);
    }

    const secret = env.CRON_SECRET?.trim();
    if (!secret) {
      const msg = "[cron] CRON_SECRET is not configured";
      console.error(msg);
      throw new Error(msg);
    }

    const service = env.WORKER_SELF_REFERENCE;
    if (!service) {
      const msg = "[cron] WORKER_SELF_REFERENCE binding is missing";
      console.error(msg);
      throw new Error(msg);
    }

    const response = await service.fetch(
      new Request(`https://internal${path}`, {
        method: "GET",
        headers: { Authorization: `Bearer ${secret}` },
      })
    );
    if (!response.ok) {
      const body = await response.text();
      const msg = `[cron] ${path} failed: ${response.status} ${body.slice(0, 500)}`;
      console.error(msg);
      throw new Error(msg);
    }
  },
};

// Required for OpenNext DO queue / tag cache (default adapter output).
// @ts-expect-error `.open-next/worker.js` is generated by `opennextjs-cloudflare build`
export {
  DOQueueHandler,
  DOShardedTagCache,
  BucketCachePurge,
} from "./.open-next/worker.js";
