// @ts-nocheck — Wrangler entry; types checked via `npm run cf-typecheck` after `npm run cf-typegen`.
/**
 * Custom Cloudflare Worker entry: re-uses OpenNext fetch handler and adds Cron Triggers.
 * @see https://opennext.js.org/cloudflare/howtos/custom-worker
 */
// @ts-expect-error `.open-next/worker.js` is generated by `opennextjs-cloudflare build`
import { default as handler } from "./.open-next/worker.js";

/** Cron expression → existing Next.js cron route (Bearer CRON_SECRET). */
const CRON_ROUTES: Record<string, string> = {
  "0 9 * * *": "/api/cron/reminders",
  "0 10 * * *": "/api/cron/sync-ideas",
  "0 11 * * *": "/api/cron/sync-git",
};

export default {
  fetch: handler.fetch,

  async scheduled(controller, env, ctx) {
    const path = CRON_ROUTES[controller.cron];
    if (!path) {
      console.error(`[cron] unknown schedule: ${controller.cron}`);
      return;
    }

    const secret = env.CRON_SECRET?.trim();
    if (!secret) {
      console.error("[cron] CRON_SECRET is not configured");
      return;
    }

    const service = env.WORKER_SELF_REFERENCE;
    if (!service) {
      console.error("[cron] WORKER_SELF_REFERENCE binding is missing");
      return;
    }

    const run = async () => {
      const response = await service.fetch(
        new Request(`https://internal${path}`, {
          method: "GET",
          headers: { Authorization: `Bearer ${secret}` },
        })
      );
      if (!response.ok) {
        const body = await response.text();
        console.error(
          `[cron] ${path} failed: ${response.status} ${body.slice(0, 500)}`
        );
      }
    };

    ctx.waitUntil(run());
  },
};

// Required for OpenNext DO queue / tag cache (default adapter output).
// @ts-expect-error `.open-next/worker.js` is generated by `opennextjs-cloudflare build`
export {
  DOQueueHandler,
  DOShardedTagCache,
  BucketCachePurge,
} from "./.open-next/worker.js";
