import { promises as fs } from "fs";
import path from "path";

let writeEnabled = false;

/** 仅 stdio 入口调用；远程 HTTP MCP 不写本地文件 */
export function enableMcpMigrationWrite() {
  writeEnabled = true;
}

export function canWriteMigrationsLocally() {
  return writeEnabled;
}

function migrationsDir() {
  return path.join(process.cwd(), "supabase", "migrations");
}

async function nextMigrationPrefix(): Promise<string> {
  const dir = migrationsDir();
  let entries: string[] = [];
  try {
    entries = await fs.readdir(dir);
  } catch {
    await fs.mkdir(dir, { recursive: true });
    entries = [];
  }
  let max = 0;
  for (const name of entries) {
    const m = name.match(/^(\d{3})_/);
    if (m) max = Math.max(max, Number(m[1]));
  }
  return String(max + 1).padStart(3, "0");
}

function slugify(slug: string) {
  return slug
    .toLowerCase()
    .replace(/[^a-z0-9_]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 48) || "schema_change";
}

export async function writeMigrationFile(slug: string, sqlBody: string) {
  const prefix = await nextMigrationPrefix();
  const fileName = `${prefix}_${slugify(slug)}.sql`;
  const fullPath = path.join(migrationsDir(), fileName);
  const content = `-- auto-generated by star-pm MCP (stdio)\n\n${sqlBody.trim()}\n`;
  await fs.writeFile(fullPath, content, "utf8");
  return { path: fullPath, fileName, prefix };
}
